name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish .NET Project
      run: dotnet publish --configuration Release --framework net8.0 --output ./publish

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: VideoProcessorTrigger
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish
