name: Build and deploy ASP.Net Core app to Azure Web App - MyWebAppSp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Build the project with the correct path
      - name: Build with dotnet
        run: dotnet build "NewSprintEvaluationAPI/SprintEvaluationAPI.csproj" --configuration Release

      # Publish the project with the correct path
      - name: dotnet publish
        run: dotnet publish "NewSprintEvaluationAPI/SprintEvaluationAPI.csproj" -c Release -o "${{github.workspace}}/myapp"

      # Upload the artifact for the deployment step
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download the artifact from the build step
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Deploy the application to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'MyWebAppSp'
          slot-name: 'Production'
          package: './myapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
